# Generated by Django 2.1.2 on 2018-10-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency',
            new_name='symbol',
        ),
    ]
