# Generated by Django 2.1.2 on 2018-10-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0002_auto_20181005_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='currency',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='node', to='custody.Currency'),
            preserve_default=False,
        ),
    ]
