# Generated by Django 2.1.2 on 2018-10-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0003_node_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='cold_storage_address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
