# Generated by Django 2.1.2 on 2018-10-18 21:21

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0006_auto_20181012_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSigAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='cold_storage_address',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(help_text='This is the public address associated with your key. Do NOT input your private key here under any circumstance!', max_length=256),
        ),
        migrations.AddField(
            model_name='multisigaddress',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cold_storage_address', to='custody.Currency'),
        ),
        migrations.AddField(
            model_name='multisigaddress',
            name='user_addresses',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='currency', chained_model_field='user_addresses', to='custody.UserAddress'),
        ),
    ]
