# Generated by Django 2.1.2 on 2018-10-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0010_auto_20181018_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='custody.Currency'),
        ),
    ]
