# Generated by Django 2.1.2 on 2018-10-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0011_auto_20181018_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigaddress',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cold_storage_addresses', to='custody.Currency'),
        ),
        migrations.AlterField(
            model_name='node',
            name='currency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='custody.Currency'),
        ),
    ]
