# Generated by Django 2.1.2 on 2018-10-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0012_auto_20181018_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigaddress',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cold_storage_address', to='custody.Currency'),
        ),
    ]
