# Generated by Django 2.1.2 on 2018-10-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0013_auto_20181018_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigaddress',
            name='user_addresses',
            field=models.ManyToManyField(to='custody.UserAddress'),
        ),
    ]
