# Generated by Django 2.1.2 on 2018-11-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0017_auto_20181112_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='required_confirmations',
        ),
    ]
