# Generated by Django 2.1.2 on 2018-11-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0019_currency_required_confirmations'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigaddress',
            name='minimum_signatures',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(help_text='This is the public key. Do NOT input your private key here under any circumstance!', max_length=256),
        ),
    ]
