# Generated by Django 2.1.2 on 2018-12-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0022_auto_20181221_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('LTC', 'Litecoin'), ('BCH', 'Bitcoin Cash'), ('ETC', 'Ethereum Classic'), ('ETH', 'Ethereum')], max_length=12, unique=True),
        ),
    ]
