# Generated by Django 2.1.2 on 2019-01-03 21:18

from django.db import connection
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    def data_migration(apps, schema_editor):
        with connection.cursor() as cursor:
            sql = "SELECT id, redeem_script FROM custody_multisigaddress"
            cursor.execute(sql)
            for row in cursor.fetchall():
                id = row[0]
                redeem_script = row[1]
                sql = """
                    UPDATE custody_multisigaddress
                    SET extra = '{"redeem_script":"%s"}'::json
                    WHERE id = '%s'
                """ % (redeem_script, id)
                cursor.execute(sql)

    dependencies = [
        ('custody', '0023_auto_20181221_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigaddress',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.RunPython(data_migration),
        migrations.RemoveField(
            model_name='multisigaddress',
            name='redeem_script',
        ),
    ]
