# Generated by Django 2.1.2 on 2019-01-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0023_auto_20181221_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='default_block_height',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
