# Generated by Django 2.1.2 on 2019-01-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0024_auto_20190103_2118'),
        ('custody', '0024_currency_default_block_height'),
    ]

    operations = [
    ]
