# Generated by Django 2.1.2 on 2019-01-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0024_currency_default_block_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='withdrawals_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
