# Generated by Django 2.1.2 on 2018-11-28 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custody', '0019_currency_required_confirmations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('multisig_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_requests', to='custody.MultiSigAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequestSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
                ('transaction_body', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signatures', to='coldstoragetransfers.TransferRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_request_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
