# Generated by Django 2.1.2 on 2018-11-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldstoragetransfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='raw_transaction_body',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
