# Generated by Django 2.1.2 on 2018-12-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldstoragetransfers', '0002_transferrequest_raw_transaction_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='txid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
