# Generated by Django 2.1.2 on 2018-12-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldstoragetransfers', '0003_transferrequest_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequestsignature',
            name='transaction_body',
            field=models.TextField(),
        ),
    ]
