# Generated by Django 2.1.2 on 2019-01-03 21:18

from django.db import connection
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    def data_migration(apps, schema_editor):
        with connection.cursor() as cursor:
            sql = "SELECT id, txid, raw_transaction_body FROM coldstoragetransfers_transferrequest"
            cursor.execute(sql)
            for row in cursor.fetchall():
                id = row[0]
                txid = row[1]
                raw_transaction_body = row[2]
                sql = """
                    UPDATE coldstoragetransfers_transferrequest
                    SET extra = '{"raw_transaction_body":"%s", "txid":"%s"}'::json
                    WHERE id = '%s'
                """ % (raw_transaction_body, txid, id)
                cursor.execute(sql)

            sql = "SELECT id, transaction_body FROM coldstoragetransfers_transferrequestsignature"
            cursor.execute(sql)
            for row in cursor.fetchall():
                id = row[0]
                transaction_body = row[1]
                sql = """
                    UPDATE coldstoragetransfers_transferrequestsignature
                    SET extra = '{"transaction_body":"%s"}'::json
                    WHERE id = '%s'
                """ % (transaction_body, id)
                cursor.execute(sql)

    dependencies = [
        ('coldstoragetransfers', '0004_auto_20181222_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transferrequestsignature',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.RunPython(data_migration),
        migrations.RemoveField(
            model_name='transferrequest',
            name='raw_transaction_body',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='txid',
        ),
        migrations.RemoveField(
            model_name='transferrequestsignature',
            name='transaction_body',
        ),
    ]
